server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackflov
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  application:
    name: StackFlov